services:

  appDb:
    image: bitnami/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: miniProject
    ports: 
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysql", "-u", "root",  "-pnokia123", "-e", "show schemas"]
      interval: 10s 

  app:
    build: .
    restart: always
    depends_on:
      appDb:
        condition: service_healthy
    environment:
      HTTP_PORT: 8880
      CONNECTION_STRING: root:nokia123@tcp(appDb:3306)/miniProject?charset=utf8&parseTime=True&loc=Local
      STORAGE: db
    ports:
      - 8880:8880

  adminer:
    image: adminer
    restart: always
    ports: # host:container
      - 8881:8880