---
name: Deploy
on:
  push:
    branches:
      - main
    # # Hanya men-trigger action jika ada perubahan di folder /controller
    paths:
      - appController/**

jobs:

  deploy-to-ec2:
    runs-on: ubuntu 20.04
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd mini-project
          git pull origin main
          cd 'fix code'
          docker-compose down
          docker-compose up --build -d
